Syslog          yes
SyslogSuccess   yes
LogWhy          yes

Canonicalization relaxed/simple
Mode            sv
SubDomains      no

AutoRestart     yes
AutoRestartRate 10/1M

Background      yes
DNSTimeout      5
SignatureAlgorithm rsa-sha256

Domain          rpow2.com
Selector        rpow2
KeyFile         /etc/opendkim/keys/rpow2.com/rpow2.private

Socket          inet:8891@localhost
PidFile         /run/opendkim/opendkim.pid
UMask           007

TrustAnchorFile /usr/share/dns/root.key
UserID          opendkim
